#%RAML 1.0
description: custom policy test api
mediaType: application/json
title: Custom policy test api


/employees:
  post:
    body: 
      application/json:
    responses: 
      200:
        body: 
          application/json: 